language: r
sudo: required

warnings_are_errors: true
before_script:
    - git config --global user.name "travis"
    - git config --global user.email "travis@example.org"

r_binary_packages:
  - devtools
  - ggplot2
  

r_github_packages:
  - rstudio/rmarkdown
 
#
