language: r
sudo: required

# for now
warnings_are_errors: false

before_install:
    - cd rethomics
before_script:
    - git config --global user.name "travis"
    - git config --global user.email "travis@example.org"

r_binary_packages:
    - ggplot2
    - data.table
  

r_github_packages:
    - rstudio/rmarkdown
 
#

#Rscript -e 'options(repos = "http://cran.rstudio.com"); deps <- devtools::install_deps(dependencies = TRUE); if (!all(deps %in% installed.packages())) {  message("missing: ", paste(setdiff(deps, installed.packages()), collapse=", "));  q(status = 1, save = "no") }'
#Rscript -e '
#options(repos = "http://cran.rstudio.com");
#deps <- devtools::install_deps(dependencies = TRUE);
#if (!all(deps %in% installed.packages())) { 
#          message("missing: ", paste(setdiff(deps, installed.packages()), collapse=", "));  
#         q(status = 1, save = "no") }
