language: r
sudo: required
warnings_are_errors: true

before_install:
    - cd rethomics
before_script:
    - git config --global user.name "travis"
    - git config --global user.email "travis@example.org"
r_binary_packages:
    - ggplot2
    - data.table
r_github_packages:
    - rstudio/rmarkdown
after_success:
    - cd ..
    # hides ghtoken from output
    - bash tools/make_tuto.sh 2>&1 | sed s/$GH_TOKEN/GH_TOKEN/g


env:
  matrix:
    secure: NIsEbodW3cOjxpcMD/K2WSSefvqsYxVAvoYc+mmF6LabVnzuUEU5RZODDLoavPYfI6Yu6vqZwnUlHLVOiMQhvVKcRiTd+GaLMXHP3WT6zWFwrosX0UG9qK9kWZzMjyZD/3uaqnmzMaHj42PZYVeIxsacBd52JCnvcUGBpJ9BctENqLwJVEIaq+2VJakLjc92W79GGMwGiGw2H2334oEaDgPCaBonXQghxGgO+Xw8cCyFcTCu33j0WO0veM1yISYcRyv7SW//GvOZrf6JxqqOzXqZLHCQtO22m4RDLX3Ua0jNosCYej9wHDw3kGWhwDCVVHes+HzKZDioNMsYXGX65TsO2iQd7hualj83ofrCxc5p++6gPvhjL49tAo4eVi+IITe30HvxjOFGuTddlesZTf+6qEdzTUgGEyBXrahWNEpwGrfQX9ycAP2U8btu2Q8xkwueuYBS6mk0W42zETsLCeotFm3uLpcocsxOzm0mScVG6ncrQDhBrm8b0ZQR59kryqgm2fA0sFtuXqkLz64UeqXFPxwGy7TkY5yLdeicMQ0CdwLGtQIK6Vgg8khXWcsKYzr96GAQB7T+WKYPcNprIw4OSMXqSp8wxltEsulqyHEoGHFn5lSjTaZPvFyROjohswtFxIkVa/OtO1jXXDVMpsUxI1CdS3BKTa4xB9zX7Yc=
