language: r
r:
  - release

  
sudo: required
dist: trusty
cache: packages
latex: false

warnings_are_errors: true

before_install:
    - cd rethomics
before_script:
    - git config --global user.name "travis"
    - git config --global user.email "travis@example.org"

#~ r_github_packages:
    #~ - hadley/devtools
    #~ - tidyverse/ggplot2
    #~ - rstudio/rmarkdown
    #~ - Rdatatable/data.table
    
script:
    - R CMD build .
    - R CMD check *tar.gz
    - cd .. 
    - echo the data lives at $RETHOMICS_TUTO_DATA 
    - bash tutorial/make_tuto.sh 2>&1
    
env:
    matrix:
        secure: j9NRGsg28uyY4bF0ANVfmspeAFRz7gZOXf1EpKOR7+L+BdxAjK+8VuS5uHMDjb2kwJy6HxVUfCaTGmn+PzjL/I5i098pl8ZXVHrd481zkYBTGubu633f4O6ADXJpx44jkkM2BVtdjS9jgqwLOojncPt2zAtsyduaV43lowU7Q2MNLQcPPt2y+uiy28ya0fEwX6ydHnJla4xIhxMH8XW2FHr1IvQrCG37oAC4ETtP8mEnQ83tlYvvJFbdke/eHOFv/UVINteoiUEk/xn59Lr5pdceyv/+zo0Brl/sru8F1zASZcnwvMFFAA1mrZJ9GFzE45283z8y+d5Mrrg32LtNGgx9dfJsL9uyat32vtiagDn6VClBdUoD2GZ5ZR6vBLmNlJvujqTr/ps7mFRmcuNcOBT6Fw4oZm+56p4EGcNGN/2mnrqWsxf3Ck97mzn6/DKJEBF0gq3a7TKDqAsDVELpxNJAaRfBh03mIgp0xlm8kzuskSP8x5QRf0Q3+vnUvBPX7Q4Iast+UfGtDo4Kb9V+o6mDI88dzxsfKLMQ9pzAC7SBZa6d6Xp4J1kHKzEqLXR5aa6p474gm0bOc6OKRT39Flsmi/g6cEEgQ0PRlp71RqCSmVSVHfzF0G/WTOsIkN7M04qzZZ+/mrSYC3z1w/jMoafmiBerkNpcCSgFBr1ff3Y=
    global:
        - RETHOMICS_TUTO_DATA=https://imperialcollegelondon.box.com/shared/static/t7osbe1rcoba7tpj262l9xsnje5b9mov.zip
